using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using AnaliseDemonstrativoTISS.Operadoras;
using AnaliseDemonstrativoTISS.Operadoras.Amil;
using AnaliseDemonstrativoTISS.Operadoras.Petrobras;
using AnaliseDemonstrativoTISS.Operadoras.Sulamerica;

namespace AnaliseDemonstrativoTISS;

public partial class MainWindow
{
    private static readonly Dictionary<string, Func<RegistroAnalise, string>> MapeamentoColunas =
        new(StringComparer.Ordinal)
        {
            [nameof(RegistroAnalise.Credencial)] = static r => r.Credencial,
            [nameof(RegistroAnalise.Nome)] = static r => r.Nome,
            [nameof(RegistroAnalise.Senha)] = static r => r.Senha,
            [nameof(RegistroAnalise.NumeroGuiaPrestador)] = static r => r.NumeroGuiaPrestador,
            [nameof(RegistroAnalise.NumeroGuiaOperadora)] = static r => r.NumeroGuiaOperadora,
            [nameof(RegistroAnalise.DataAtendimento)] = static r => r.DataAtendimento,
            [nameof(RegistroAnalise.CodigoProcedimento)] = static r => r.CodigoProcedimento,
            [nameof(RegistroAnalise.DescricaoProcedimento)] = static r => r.DescricaoProcedimento,
            [nameof(RegistroAnalise.Quantidade)] = static r => r.Quantidade,
            [nameof(RegistroAnalise.ValorInformado)] = static r => r.ValorInformado,
            [nameof(RegistroAnalise.ValorProcessado)] = static r => r.ValorProcessado,
            [nameof(RegistroAnalise.ValorLiberado)] = static r => r.ValorLiberado,
            [nameof(RegistroAnalise.ValorGlosa)] = static r => r.ValorGlosa,
            [nameof(RegistroAnalise.CodigoGlosa)] = static r => r.CodigoGlosa,
            [nameof(RegistroAnalise.DescricaoGlosa)] = static r => r.DescricaoGlosa,
            [nameof(RegistroAnaliseSulamerica.SituacaoGuia)] = static r => r is RegistroAnaliseSulamerica sulamerica ? sulamerica.SituacaoGuia : string.Empty,
            [nameof(RegistroAnalisePetrobras.TipoPagamento)] = static r => r is RegistroAnalisePetrobras petrobras ? petrobras.TipoPagamento : string.Empty,
            [nameof(RegistroAnaliseAmil.CodigoGlosaAmil)] = static r => r is RegistroAnaliseAmil amil ? amil.CodigoGlosaAmil : string.Empty,
            [nameof(RegistroAnaliseAmil.DescricaoGlosaAmil)] = static r => r is RegistroAnaliseAmil amil ? amil.DescricaoGlosaAmil : string.Empty
        };

    private static readonly Dictionary<string, int> OrdemColunas = new(StringComparer.Ordinal)
    {
        [nameof(RegistroAnalise.Credencial)] = 0,
        [nameof(RegistroAnalise.Nome)] = 1,
        [nameof(RegistroAnalise.Senha)] = 2,
        [nameof(RegistroAnalise.NumeroGuiaPrestador)] = 3,
        [nameof(RegistroAnalise.NumeroGuiaOperadora)] = 4,
        [nameof(RegistroAnalise.DataAtendimento)] = 5,
        [nameof(RegistroAnalise.CodigoProcedimento)] = 6,
        [nameof(RegistroAnalise.DescricaoProcedimento)] = 7,
        [nameof(RegistroAnalise.Quantidade)] = 8,
        [nameof(RegistroAnalise.ValorInformado)] = 9,
        [nameof(RegistroAnalise.ValorProcessado)] = 10,
        [nameof(RegistroAnalise.ValorLiberado)] = 11,
        [nameof(RegistroAnalise.ValorGlosa)] = 12,
        [nameof(RegistroAnalise.CodigoGlosa)] = 13,
        [nameof(RegistroAnalise.DescricaoGlosa)] = 14,
        [nameof(RegistroAnaliseSulamerica.SituacaoGuia)] = 15,
        [nameof(RegistroAnalisePetrobras.TipoPagamento)] = 15,
        [nameof(RegistroAnaliseAmil.CodigoGlosaAmil)] = 15,
        [nameof(RegistroAnaliseAmil.DescricaoGlosaAmil)] = 16
    };

    private static readonly HashSet<string> ColunasAlinhadasEsquerda =
    [
        nameof(RegistroAnalise.Nome),
        nameof(RegistroAnalise.DescricaoGlosa),
        nameof(RegistroAnalise.DescricaoProcedimento),
        nameof(RegistroAnaliseAmil.DescricaoGlosaAmil)
    ];

    private IReadOnlyList<RegistroAnalise> _ultimoResultado = [];

    private void ResultDataGrid_LoadingRow(object sender, DataGridRowEventArgs e)
    {
        e.Row.Tag = (e.Row.GetIndex() + 1).ToString();
    }

    private void ResultDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
    {
        ConfigurarColunaSequencial();

        if (_ultimoResultado.Count == 0)
        {
            return;
        }

        foreach (var coluna in ResultDataGrid.Columns.OfType<DataGridBoundColumn>())
        {
            if (coluna.Binding is not Binding { Path.Path: { } nomePropriedade })
            {
                continue;
            }

            var alinharEsquerda = DeveAlinharEsquerda(nomePropriedade);
            coluna.CellStyle = (Style)FindResource(alinharEsquerda ? "LeftAlignedDataGridCellStyle" : "ResultDataGridCellStyle");
            coluna.HeaderStyle = (Style)FindResource(alinharEsquerda ? "LeftAlignedDataGridHeaderStyle" : "ResultDataGridHeaderStyle");

            if (coluna is DataGridTextColumn colunaTextoBase)
            {
                colunaTextoBase.ElementStyle = (Style)FindResource(alinharEsquerda ? "LeftAlignedDataGridTextStyle" : "CenteredDataGridTextStyle");
            }

            if (!MapeamentoColunas.TryGetValue(nomePropriedade, out var seletorValor))
            {
                continue;
            }

            var possuiValor = _ultimoResultado.Any(registro => !string.IsNullOrWhiteSpace(seletorValor(registro)));
            coluna.Visibility = possuiValor ? Visibility.Visible : Visibility.Collapsed;

            if (OrdemColunas.TryGetValue(nomePropriedade, out var ordem))
            {
                coluna.DisplayIndex = ordem + 1;
            }
        }
    }

    private void ConfigurarColunaSequencial()
    {
        var colunaSequencial = ResultDataGrid.Columns.OfType<DataGridTemplateColumn>().FirstOrDefault();
        if (colunaSequencial is null)
        {
            return;
        }

        colunaSequencial.DisplayIndex = 0;
    }

    private bool DeveAlinharEsquerda(string nomePropriedade)
    {
        return ColunasAlinhadasEsquerda.Contains(nomePropriedade);
    }
}
